# Site settings
title: Lillian Behm
author:
  email: your-email@domain.com
description: "Lily is a PhD student in the Turk-Browne lab at Yale University"

# Build settings
remote_theme: jekyll/minima
